tweets/urls.py
from django.urls import path
from . import views

app_name = "tweets"

urlpatterns = [
    path("", views.create_tweet, name="create_tweet"),
    path('<int:pk>', views.detail_tweet, name="detail_tweet"),
    path("/update/<int:pk>", views.update_tweet, name="update_tweet"),
    path("<int:pk>/delete", views.delete_tweet, name="delete_tweet")
]

twitter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("tweets.urls"))
]

tweets/models.py
from django.db import models


# Create your models here.
class Tweet(models.Model):
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[:20]

tweets/forms.py
from django.forms import ModelForm
from .models import Tweet


class TweetForm(ModelForm):
    class Meta:
        model = Tweet
        fields = "__all__"
        labels = {
            'text': "Tweet here"  # _("Enter your tweet here")
        }

tweets/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404

from .forms import TweetForm
from .models import Tweet


# Create your views here.
def create_tweet(request):
    if request.method == 'POST':
        form = TweetForm(data=request.POST)

        if form.is_valid():
            form.save()
            form = TweetForm()
    else:
        form = TweetForm()

    tweets = Tweet.objects.all()
    context = {
        "form": form,
        "tweets": tweets
    }
    return render(request, "tweets/index.html", context)


def detail_tweet(request, pk):
    tweet = Tweet.objects.get(pk=pk)
    context = {'tweet': tweet}
    return render(request, 'tweets/detail_view.html', context)


def update_tweet(request, pk):
    tweet_to_update = get_object_or_404(Tweet, pk=pk)

    form = TweetForm(request.POST or None, instance=tweet_to_update)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/" + str(pk))

    context = {
        "form": form
    }

    return render(request, "tweets/update_view.html", context)


def delete_tweet(request, pk):
    tweet_to_delete = get_object_or_404(Tweet, pk=pk)

    if request.method == 'POST':
        tweet_to_delete.delete()

        return HttpResponseRedirect("/")
    return render(request, "tweets/delete_view.html")

tweets/templates/tweets/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tweeter</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}" type="text/css">
    <script src="https://kit.fontawesome.com/e2052a1ca7.js" crossorigin="anonymous"></script>
</head>
<body>
<h1 class="logo"><a href="/">tweeter</a></h1>

{% block container %}
{% endblock %}

<script>
if ( window.history.replaceState ) {
  window.history.replaceState( null, null, window.location.href );
}
</script>
</body>
</html>

tweets/templates/tweets/delete_view.html
{% extends 'tweets/base.html' %}
{% block container %}
    <form method="post" class="del-form">
        {% csrf_token %}
        <p class="confirmation-message">Are you sure you want to delete this tweet ?</p>
        <div class="del-btn">
            <button class="delete btn" type="submit">Yes</button>
            <a href="/" class="btn">Cancel</a>
        </div>
    </form>
{% endblock %}

tweets/templates/tweets/detail_view.html
{% extends 'tweets/base.html' %}
{% load static %}
{% block container %}
    <div class="tweet">
        <div class="user-detail">
            <div class="user-info">
                <img src="{% static 'images/user.png' %}" alt="user-avatar" class="user-pic">
                <h2 class="name"></h2>
                <p class="username"></p>
            </div>

            <div class="follow">
                <input type="submit" name="submit" value="follow" disabled>
                <a href="{% url 'tweets:detail_tweet' tweet.pk %}" class="detail">view</a>
                <a href="{% url 'tweets:update_tweet' tweet.pk %}" class="update">edit</a>
                <a href="{% url 'tweets:delete_tweet' tweet.pk %}" class="delete">delete</a>
            </div>
        </div>
        <h4>{{ tweet.text }}</h4>
        <div class="tweet-interaction">
            <a href="#">Love</a>
            <a href="#">Retweet</a>
            <p> {{ tweet.date_added }}</p>
        </div>

    </div>
{% endblock %}

tweets/templates/tweets/index.html
{% extends 'tweets/base.html' %}
{% load static %}
{% block container %}
    <form action="{% url 'tweets:create_tweet' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="Tweet" name="submit">
    </form>

    {% for tweet in tweets %}
        <div class="tweet">
            <div class="user-detail">
                <div class="user-info">
                    <img src="{% static 'images/user.png' %}" alt="user-avatar" class="user-pic">
                    <h2 class="name"></h2>
                    <p class="username"></p>
                </div>

                <div class="follow">
                    <input type="submit" name="submit" value="follow" disabled>
                    <a href="{% url 'tweets:detail_tweet' tweet.pk %}" class="detail">view</a>
                    <a href="{% url 'tweets:update_tweet' tweet.pk %}" class="update">edit</a>
                    <a href="{% url 'tweets:delete_tweet' tweet.pk %}" class="delete">delete</a>
                </div>
            </div>
            <h4>{{ tweet.text }}</h4>
            <div class="tweet-interaction">
                <a href="#">Love</a>
                <a href="#">Like</a>
                <p> {{ tweet.date_added }}</p>
            </div>

        </div>
    {% endfor %}
{% endblock %}

tweets/templates/tweets/update_view.html
{% extends 'tweets/base.html' %}
{% block container %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Tweet" name="submit">
    </form>

{% endblock %}